### ISSUE TITLE
opam and ppx

### ISSUE THREAD

**Issue by idkjs** [drejohnson/reason-apollo-graphql_ppx-test#1]
Greetings @drejohnson. General question about your set up.

How do you have opam set up with bs-platform. Generally, they seem to run into each other if you have both installed. Do you mind sharing how you have them both set up on your machine?

Thank you.

**Comment by idkjs** [comment]
Seems like the solution is to have reason set up with the alternative set up per discord discussion just now. This seems to work. https://reasonml.github.io/docs/en/global-installation.html#alternative-through-opam

**Comment by drejohnson** [comment]
I installed binary dist for Linux from https://opam.ocaml.org/doc/Install.html. I had bs-platform installed globally through npm

**Comment by drejohnson** [comment]
Also, many changes have been introduced to reason-apollo since I made this.So it won't work without updating to the latest version and make a few changes to Client.re

**Comment by idkjs** [comment]
You have been killing it, boss. Keep up the grind!
